/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as DoneRouteImport } from './routes/done'
import { Route as HowRouteImport } from './routes/how'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiIceRouteImport } from './routes/api/ice'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiSparkRouteImport } from './routes/api/spark'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as ArchiveStoryIdRouteImport } from './routes/archive/$storyId'
import { Route as RoomCodeRouteImport } from './routes/room/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIceRoute = ApiIceRouteImport.update({
  id: '/api/ice',
  path: '/api/ice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSparkRoute = ApiSparkRouteImport.update({
  id: '/api/spark',
  path: '/api/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveStoryIdRoute = ArchiveStoryIdRouteImport.update({
  id: '/archive/$storyId',
  path: '/archive/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/done': typeof DoneRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/spark': typeof ApiSparkRoute
  '/archive/$storyId': typeof ArchiveStoryIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/done': typeof DoneRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/spark': typeof ApiSparkRoute
  '/archive/$storyId': typeof ArchiveStoryIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/done': typeof DoneRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/spark': typeof ApiSparkRoute
  '/archive/$storyId': typeof ArchiveStoryIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circle'
    | '/done'
    | '/how'
    | '/play'
    | '/remote'
    | '/settings'
    | '/api/ice'
    | '/api/rtc'
    | '/api/spark'
    | '/archive/$storyId'
    | '/room/$code'
    | '/archive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circle'
    | '/done'
    | '/how'
    | '/play'
    | '/remote'
    | '/settings'
    | '/api/ice'
    | '/api/rtc'
    | '/api/spark'
    | '/archive/$storyId'
    | '/room/$code'
    | '/archive'
  id:
    | '__root__'
    | '/'
    | '/circle'
    | '/done'
    | '/how'
    | '/play'
    | '/remote'
    | '/settings'
    | '/api/ice'
    | '/api/rtc'
    | '/api/spark'
    | '/archive/$storyId'
    | '/room/$code'
    | '/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircleRoute: typeof CircleRoute
  DoneRoute: typeof DoneRoute
  HowRoute: typeof HowRoute
  PlayRoute: typeof PlayRoute
  RemoteRoute: typeof RemoteRoute
  SettingsRoute: typeof SettingsRoute
  ApiIceRoute: typeof ApiIceRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiSparkRoute: typeof ApiSparkRoute
  ArchiveStoryIdRoute: typeof ArchiveStoryIdRoute
  RoomCodeRoute: typeof RoomCodeRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ice': {
      id: '/api/ice'
      path: '/api/ice'
      fullPath: '/api/ice'
      preLoaderRoute: typeof ApiIceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spark': {
      id: '/api/spark'
      path: '/api/spark'
      fullPath: '/api/spark'
      preLoaderRoute: typeof ApiSparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$storyId': {
      id: '/archive/$storyId'
      path: '/archive/$storyId'
      fullPath: '/archive/$storyId'
      preLoaderRoute: typeof ArchiveStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircleRoute: CircleRoute,
  DoneRoute: DoneRoute,
  HowRoute: HowRoute,
  PlayRoute: PlayRoute,
  RemoteRoute: RemoteRoute,
  SettingsRoute: SettingsRoute,
  ApiIceRoute: ApiIceRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiSparkRoute: ApiSparkRoute,
  ArchiveStoryIdRoute: ArchiveStoryIdRoute,
  RoomCodeRoute: RoomCodeRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
